### ISSUE TITLE
Import framework to swift project

### ISSUE THREAD

**Issue by snowtema** [yandexmobile/yandex-speechkit-ios#7]
How can I import YandexSpeechKit.framework to my swift project with cocoapods?

**Comment by asyaKononova** [comment]
Hi, add to your Podfile `pod 'YandexSpeechKit', '~> 3.12.2'`, run `pod install`, than add [bridging header](https://stackoverflow.com/questions/24002369/how-to-call-objective-c-code-from-swift?answertab=active#tab-top) to your project for importing obj-c files to swift. If you already have it, just add `#import < YandexSpeechKit/YandexSpeechKit.h>` line.

**Comment by snowtema** [comment]
Hi @asyaKononova! Thank you
